language: node_js
node_js: lts/*
services:
- docker
script:
- docker build -t bergie/shell ./
deploy:
  -
    provider: script
    script: bash utils/docker_push
    on:
      branch: master
  -
    provider: script
    script: bash utils/docker_push
    on:
      tags: true
env:
  global:
  - secure: ecstHKFzuadZNwtCypRyRBF3So4QzX+/fcd/IVb7HeBoCEuu9+5tePBaakPmUKryaCOh/s1/VGsXnHH2uM0xIOljmr/DUQV1SmwWSyoV1BCxlfZV3IDqNCO293EfG4hFZuIhT1WsbPAazf94zI/vQN9sht3Eln06/PMI065g39E=
  - secure: Hp9qrgGbWZjB3yGQpfTppdkwgt7UN/UQA3LYrL7VttY/tgvH5IGImmY3VUnwjVN8iSjJ0wgVbRAGQZfcV2sPYl9Skk3deJ7nrWeKlRVfCxyg2RgMoYFKC4qiuhE9XwBq3xwblxoSpRpnbEZMuuUVzirqSBngWOWr2yyJmcd3pkY=
notifications:
  email:
    on_success: never
    on_failure: always
